services:
  app:
    image: 'ghcr.io/un1uckyyy/fast-api-fa:dev'
    environment:
      DEBUG: true
      DATABASE_URL: 'sqlite:///sem2.db'
      SECRET_KEY: $SECRET_KEY
      ALGORITHM: $ALGORITHM
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - '8000:8000'
